services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: my_ai_chatbot_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql+psycopg2://postgres:postgres@db:5432/ai_chatbot
      - ELASTICSEARCH_URL=http://11.0.0.109:9200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - .:/app
    command: >
      sh -c "uv run alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:16-alpine
    container_name: my_ai_chatbot_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
